[project]
name = "zitcompiler"
version = "0.1.0"
description = "A Zig zust-in-time compiler for Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["ziglang"]

[project.optional-dependencies]
cli = ["click"]
tests = ["pytest", "nox"]
benchmarks = ["pytest-benchmark", "rich"]
build = ["hatchling"]

[project.scripts]
zit = "zitcompiler.cli:zit"

[project.entry-points.hatch]
zitcompiler = "zitcompiler.build_backend.hatch"
